sensors:
  - bucket: "processing-artifacts"
    directory: "manufacturing"
    config:
      ops:
        build_knowledge_graph:
          config:
            graph_node_label: "Part"
            graph_child_label: "ManufacturingStep"
            vector_collection_name: "ManufacturingStep"
  - bucket: "processing-artifacts"
    directory: "compliance"
    config:
      ops:
        build_knowledge_graph:
          config:
            graph_node_label: "Regulation"
            graph_child_label: "ComplianceRule"
            vector_collection_name: "ComplianceRule"
  - bucket: "processing-artifacts"
    directory: "training"
    config:
      ops:
        build_knowledge_graph:
          config:
            graph_node_label: "Course"
            graph_child_label: "Slide"
            vector_collection_name: "TrainingCourse"
