sensors:
  - bucket: "processing-artifacts"
    directory: "manufacturing"
    config:
      ops:
        build_knowledge_graph:
          config:
            graph_node_label: "WorkInstruction"
            graph_child_label: "Page"
            vector_collection_name: "ManufacturingDocumentChunk"
  - bucket: "processing-artifacts"
    directory: "compliance"
    config:
      ops:
        build_knowledge_graph:
          config:
            graph_node_label: "RegulationDocument"
            graph_child_label: "Page"
            vector_collection_name: "ComplianceDocumentChunk"
  - bucket: "processing-artifacts"
    directory: "training"
    config:
      ops:
        build_knowledge_graph:
          config:
            graph_node_label: "Course"
            graph_child_label: "Slide"
            vector_collection_name: "TrainingDocumentChunk"
