apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "doc-tools.fullname" . }}-config
  labels:
    {{- include "doc-tools.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.runConfig | indent 4 }}
