# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractComplianceRules(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ComplianceAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractComplianceRules", llm_response=llm_response, mode="request")
        return typing.cast(types.ComplianceAugmentation, __result__)

    def ExtractConcepts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SlideAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractConcepts", llm_response=llm_response, mode="request")
        return typing.cast(types.SlideAugmentation, __result__)

    def ExtractMaintenanceProcedures(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MroAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMaintenanceProcedures", llm_response=llm_response, mode="request")
        return typing.cast(types.MroAugmentation, __result__)

    def ExtractOutline(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Outline:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractOutline", llm_response=llm_response, mode="request")
        return typing.cast(types.Outline, __result__)

    def ExtractSustainment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SustainmentNotice:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractSustainment", llm_response=llm_response, mode="request")
        return typing.cast(types.SustainmentNotice, __result__)

    def ExtractWorkInstructions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MatAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractWorkInstructions", llm_response=llm_response, mode="request")
        return typing.cast(types.MatAugmentation, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractComplianceRules(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ComplianceAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractComplianceRules", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ComplianceAugmentation, __result__)

    def ExtractConcepts(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SlideAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractConcepts", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SlideAugmentation, __result__)

    def ExtractMaintenanceProcedures(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MroAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractMaintenanceProcedures", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MroAugmentation, __result__)

    def ExtractOutline(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Outline:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractOutline", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Outline, __result__)

    def ExtractSustainment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SustainmentNotice:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractSustainment", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SustainmentNotice, __result__)

    def ExtractWorkInstructions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MatAugmentation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractWorkInstructions", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MatAugmentation, __result__)

    