# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ComplianceAugmentation": types.ComplianceAugmentation,
    "stream_types.ComplianceAugmentation": stream_types.ComplianceAugmentation,

    "types.ComplianceRule": types.ComplianceRule,
    "stream_types.ComplianceRule": stream_types.ComplianceRule,

    "types.Concept": types.Concept,
    "stream_types.Concept": stream_types.Concept,

    "types.LearningObjective": types.LearningObjective,
    "stream_types.LearningObjective": stream_types.LearningObjective,

    "types.ManufacturingStep": types.ManufacturingStep,
    "stream_types.ManufacturingStep": stream_types.ManufacturingStep,

    "types.MatAugmentation": types.MatAugmentation,
    "stream_types.MatAugmentation": stream_types.MatAugmentation,

    "types.Outline": types.Outline,
    "stream_types.Outline": stream_types.Outline,

    "types.Section": types.Section,
    "stream_types.Section": stream_types.Section,

    "types.SlideAugmentation": types.SlideAugmentation,
    "stream_types.SlideAugmentation": stream_types.SlideAugmentation,

    "types.StrategicAssessment": types.StrategicAssessment,
    "stream_types.StrategicAssessment": stream_types.StrategicAssessment,


    "types.HazardClass": types.HazardClass,

    "types.PersonnelRole": types.PersonnelRole,

    "types.ProcessCategory": types.ProcessCategory,

}