# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (6)
# #########################################################################

class ChangeCategory(str, Enum):
    Material = "Material"
    Process = "Process"
    Location = "Location"
    Discontinuation = "Discontinuation"
    Packaging = "Packaging"
    Testing = "Testing"

class HazardClass(str, Enum):
    pass

class InspectionType(str, Enum):
    pass

class MaintenanceLevel(str, Enum):
    pass

class PersonnelRole(str, Enum):
    pass

class ProcessCategory(str, Enum):
    pass

# #########################################################################
# Generated classes (14)
# #########################################################################

class ComplianceAugmentation(BaseModel):
    rules: typing.List["ComplianceRule"]

class ComplianceRule(BaseModel):
    manual_reference: str = Field(description='e.g. \'DAFMAN 21-201 Section 4.2\' - The source manual or regulatory document reference.')
    rule_type: str = Field(description='e.g. \'Safety\', \'Throughput\', \'Storage\', \'Certification\' - The category of the compliance rule.')
    applicable_hazard_class: typing.Optional[str] = Field(default=None, description='e.g. \'1.1D\', \'1.3\' - The explosives hazard class this rule targets. If none, leave null.')
    target_metric: typing.Optional[str] = Field(default=None, description='e.g. \'Max 5 Units\', \'< 15 mins\' - The quantitative or qualitative metric mandated by the rule.')
    rule_description: str = Field(description='A concise summary of what the rule requires.')

class Concept(BaseModel):
    name: str
    description: str
    related_terms: typing.List[str]
    salience: float

class LearningObjective(BaseModel):
    description: str

class MaintenanceStep(BaseModel):
    procedure_id: str = Field(description='The parent maintenance procedure this step belongs to')
    step_id: str = Field(description='The specific step identifier')
    instruction_text: str = Field(description='The full, verbatim raw text of the step from the document.')
    action_verb: str = Field(description='The concrete maintenance action, e.g. \'Remove\', \'Install\', \'Inspect\', \'Lubricate\', \'Torque\'')
    tooling: typing.List[str] = Field(description='List of tools required, e.g. [\'Torque Wrench\', \'Multimeter\']. If missing, empty list.')
    consumables: typing.List[str] = Field(description='Consumable materials, e.g. [\'MIL-PRF-81322 Grease\', \'Loctite 242\']. If missing, empty list.')
    hazard_class: typing.Optional[str] = Field(default=None, description='Safety hazard classification. If none, leave null.')
    required_cert: typing.Optional[str] = Field(default=None, description='Personnel certification requirement. If none, leave null.')
    standard_ref: typing.Optional[str] = Field(default=None, description='e.g. \'TM 9-1005-317-23\'. If none, leave null.')
    inspection_type: typing.Optional[typing.Union[InspectionType, str]] = Field(default=None, description='Type of inspection if this is an inspection step. If not an inspection, leave null.')
    maintenance_level: typing.Optional[typing.Union[MaintenanceLevel, str]] = Field(default=None, description='Organizational, Direct Support, or Depot level. If unclear, leave null.')
    is_safety_critical: bool = Field(description='True if the step involves high-voltage, explosive ordnance, load-bearing components, or flight-critical systems.')
    torque_spec: typing.Optional[str] = Field(default=None, description='Extract any torque specifications mentioned (e.g., \'15 ft-lbs\', \'20 Nm\'). If none, leave null.')
    justification: str = Field(description='A 1-sentence explanation of why the safety-critical flag was chosen.')
    estimated_duration_minutes: typing.Optional[int] = Field(default=None, description='Extract any mentioned time constraints or labor durations. If none, leave null.')
    military_and_industry_standards: typing.List[str] = Field(description='Extract formal standards: Military (MIL-, TM-, TM 9-*, FM-), Industry (SAE-, ANSI-, ISO-). Normalize to use a single hyphen between prefix and number. Return empty array if none.')
    internal_part_numbers: typing.List[str] = Field(description='Extract internal part numbers, NSNs, or drawing numbers explicitly mentioned. Strip prefixes; return the alphanumeric identifier.')
    figure_references: typing.List[str] = Field(description='Extract ONLY explicit figure, image, graphic, or drawing identifiers referenced in this step. Valid examples: \'Figure 3\', \'Fig. 12A\', \'Graphic 7\'. Extract the identifier only (e.g., \'3\', \'12A\', \'7\'). Do NOT extract vague references. Return empty array if no explicit figure ID is present.')

class ManufacturingStep(BaseModel):
    model_config = ConfigDict(extra='allow')
    procedure_id: str = Field(description='The parent procedure this step belongs to')
    step_id: str = Field(description='The specific step identifier')
    instruction_text: str = Field(description='The full, verbatim raw text of the step from the document.')
    action_verb: str = Field(description='The concrete action to take, e.g. \'Tighten bolt\'')
    tooling: typing.List[str] = Field(description='List of tools required, e.g. [\'Wrench\', \'Torque\'] If missing, empty list.')
    consumables: typing.List[str] = Field(description='Consumable materials, e.g. [\'Sealant MIL-S-81733\']. If missing, empty list.')
    hazard_class: typing.Optional[typing.Union[HazardClass, str]] = Field(default=None, description='Explosives Safety Hazard. If none, leave null.')
    required_cert: typing.Optional[typing.Union[PersonnelRole, str]] = Field(default=None, description='Quality/Personnel requirement. If none, leave null.')
    standard_ref: typing.Optional[str] = Field(default=None, description='e.g. \'ISO-9001\'. If none, leave null.')
    is_value_added: bool = Field(description='True ONLY if the step physically transforms the product (e.g., machining, curing, applying sealant). False if it is an inspection, movement, or waiting.')
    is_safety_critical: bool = Field(description='CRITICAL: True if the step involves static grounding, explosive hazard mitigation (Class 1.1, 1.3), environmental safety, or regulatory sign-offs. False otherwise.')
    process_category: typing.Union[ProcessCategory, str] = Field(description='The functional category of the manufacturing process.')
    justification: str = Field(description='A 1-sentence explanation of why the value-added and safety-critical flags were chosen.')
    estimated_duration_minutes: typing.Optional[int] = Field(default=None, description='Extract any mentioned time constraints, cure times, or labor durations. If none, leave null.')
    military_and_industry_standards: typing.List[str] = Field(description='Extract formal standards: Military (MIL-, MS, AN*, NAS*, AS*), Joint Industry (J-STD-*), Electronics (IPC-*), Testing (ASTM-, SAE-, ANSI-, ISO-), Process (NADCAP*). Normalize to use a single hyphen between prefix and number (e.g., \'J STD 001\', \'JSTD001\' -> \'J-STD-001\', \'MIL PRF 81733\' -> \'MIL-PRF-81733\'). Return empty array if none.')
    internal_part_numbers: typing.List[str] = Field(description='Extract internal proprietary part numbers, assembly numbers, or drawing numbers explicitly mentioned (e.g., \'PN 99-812\', \'Assy 104-B\'). Strip the \'PN\' prefix; return the alphanumeric identifier.')
    material_and_hardware_slang: typing.List[str] = Field(description='Extract generic nouns for consumables/hardware lacking a specific part number (e.g., \'RTV Silicone\', \'Loctite\', \'Hex Nut\', \'Epoxy\'). Used for downstream vector similarity searches against a materials index.')
    figure_references: typing.List[str] = Field(description='Extract ONLY explicit figure, image, graphic, or drawing identifiers referenced in this step. Valid examples: \'Figure 3\', \'Fig. 12A\', \'Graphic 7\', \'Drawing 101-B\'. Extract the identifier only (e.g., \'3\', \'12A\', \'7\', \'101-B\'). Do NOT extract vague references like \'see the diagram below\' or \'as illustrated\'. Return empty array if no explicit figure ID is present.')

class MatAugmentation(BaseModel):
    steps: typing.List["ManufacturingStep"]
    assessment: "StrategicAssessment"

class MroAugmentation(BaseModel):
    steps: typing.List["MaintenanceStep"]

class Outline(BaseModel):
    sections: typing.List["Section"]

class PartImpact(BaseModel):
    affected_mpn: str
    replacement_mpn: typing.Optional[str] = None
    ltb_date: typing.Optional[str] = Field(default=None, description='Last Time Buy Date in ISO 8601 (YYYY-MM-DD)')

class Section(BaseModel):
    title: str
    level: int
    start_page: int = Field(description='The page number where this section begins based on the Table of Contents or page markers')
    end_page: typing.Optional[int] = Field(default=None, description='The page number where this section ends')
    subsections: typing.List["Section"]

class SlideAugmentation(BaseModel):
    concepts: typing.List["Concept"]
    objectives: typing.List["LearningObjective"]
    summary: str
    figure_references: typing.List[str] = Field(description='Extract explicit figure, diagram, or graphic identifiers referenced in the slide text (e.g., \'Figure 4\', \'ICN-12345\', \'Diagram 2A\'). Do NOT extract vague references like \'see the image below\'. Return empty array if none.')

class StrategicAssessment(BaseModel):
    proprietary_score: float = Field(description='0.0 (Common) to 1.0 (Secret Sauce). Score based on how specific/complex the process is.')
    outsourceable: bool = Field(description='If it requires secret sauce or highly sensitive MAT, true. Default to false if unclear.')

class SustainmentNotice(BaseModel):
    doc_id: str = Field(description='The PCN/PDN number, e.g., 23-002')
    doc_type: str = Field(description='PCN or PDN')
    pub_date: str = Field(description='The notification date')
    mfr: str = Field(description='The manufacturer, e.g., Mini-Circuits')
    categories: typing.List[ChangeCategory]
    summary: str = Field(description='High-level impact summary (1-2 sentences)')
    impacted_parts: typing.List["PartImpact"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
