# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (10)
# #########################################################################

class ComplianceAugmentation(BaseModel):
    rules: typing.List["ComplianceRule"]

class ComplianceRule(BaseModel):
    manual_reference: str = Field(description='e.g. \'DAFMAN 21-201 Section 4.2\' - The source manual or regulatory document reference.')
    rule_type: str = Field(description='e.g. \'Safety\', \'Throughput\', \'Storage\', \'Certification\' - The category of the compliance rule.')
    applicable_hazard_class: typing.Optional[str] = Field(default=None, description='e.g. \'1.1D\', \'1.3\' - The explosives hazard class this rule targets. If none, leave null.')
    target_metric: typing.Optional[str] = Field(default=None, description='e.g. \'Max 5 Units\', \'< 15 mins\' - The quantitative or qualitative metric mandated by the rule.')
    rule_description: str = Field(description='A concise summary of what the rule requires.')

class Concept(BaseModel):
    name: str
    description: str
    related_terms: typing.List[str]
    salience: float

class LearningObjective(BaseModel):
    description: str

class ManufacturingStep(BaseModel):
    procedure_id: str = Field(description='The parent procedure this step belongs to')
    step_id: str = Field(description='The specific step identifier')
    instruction_text: str = Field(description='The full, verbatim raw text of the step from the document.')
    action_verb: str = Field(description='The concrete action to take, e.g. \'Tighten bolt\'')
    tooling: typing.List[str] = Field(description='List of tools required, e.g. [\'Wrench\', \'Torque\'] If missing, empty list.')
    consumables: typing.List[str] = Field(description='Consumable materials, e.g. [\'Sealant MIL-S-81733\']. If missing, empty list.')
    hazard_class: typing.Optional[str] = Field(default=None, description='Explosives Safety Hazard. If none, leave null.')
    required_cert: typing.Optional[str] = Field(default=None, description='Quality/Personnel requirement. If none, leave null.')
    standard_ref: typing.Optional[str] = Field(default=None, description='e.g. \'ISO-9001\'. If none, leave null.')
    is_value_added: bool = Field(description='True ONLY if the step physically transforms the product (e.g., machining, curing, applying sealant). False if it is an inspection, movement, or waiting.')
    is_safety_critical: bool = Field(description='CRITICAL: True if the step involves static grounding, explosive hazard mitigation (Class 1.1, 1.3), environmental safety, or regulatory sign-offs. False otherwise.')
    process_category: str = Field(description='The functional category of the manufacturing process.')
    justification: str = Field(description='A 1-sentence explanation of why the value-added and safety-critical flags were chosen.')
    estimated_duration_minutes: typing.Optional[int] = Field(default=None, description='Extract any mentioned time constraints, cure times, or labor durations. If none, leave null.')
    military_and_industry_standards: typing.List[str] = Field(description='Extract formal standards: Military (MIL-, MS, AN*, NAS*, AS*), Joint Industry (J-STD-*), Electronics (IPC-*), Testing (ASTM-, SAE-, ANSI-, ISO-), Process (NADCAP*). Normalize to use a single hyphen between prefix and number (e.g., \'J STD 001\', \'JSTD001\' -> \'J-STD-001\', \'MIL PRF 81733\' -> \'MIL-PRF-81733\'). Return empty array if none.')
    internal_part_numbers: typing.List[str] = Field(description='Extract internal proprietary part numbers, assembly numbers, or drawing numbers explicitly mentioned (e.g., \'PN 99-812\', \'Assy 104-B\'). Strip the \'PN\' prefix; return the alphanumeric identifier.')
    material_and_hardware_slang: typing.List[str] = Field(description='Extract generic nouns for consumables/hardware lacking a specific part number (e.g., \'RTV Silicone\', \'Loctite\', \'Hex Nut\', \'Epoxy\'). Used for downstream vector similarity searches against a materials index.')

class MatAugmentation(BaseModel):
    steps: typing.List["ManufacturingStep"]
    assessment: "StrategicAssessment"

class Outline(BaseModel):
    sections: typing.List["Section"]

class Section(BaseModel):
    title: str
    level: int
    start_page: int = Field(description='The page number where this section begins based on the Table of Contents or page markers')
    end_page: typing.Optional[int] = Field(default=None, description='The page number where this section ends')
    subsections: typing.List["Section"]

class SlideAugmentation(BaseModel):
    concepts: typing.List["Concept"]
    objectives: typing.List["LearningObjective"]
    summary: str

class StrategicAssessment(BaseModel):
    proprietary_score: float = Field(description='0.0 (Common) to 1.0 (Secret Sauce). Score based on how specific/complex the process is.')
    outsourceable: bool = Field(description='If it requires secret sauce or highly sensitive MAT, true. Default to false if unclear.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
