#!/usr/bin/env python
"""Project ``KIND_MAPPING`` into the SDK-shaped registration rows the picker reads.

ARCHITECT RULING 2026-10-02: *"7f registers the shipping kinds (PDF,
EngineeringDocument, PCN, PDN, S1000D-data-module) with their domains, as the
kind-registration rows the picker derives from."*

WHY GENERATED AND NOT HAND-MAINTAINED. ``iagent_mesh.ingest.registered_kinds``
makes the picker's legal set *be* the registered rows. If those rows were typed
out by hand beside ``doc_tools/utils/content_kind.py``'s table, the two could
disagree — and the failure mode is the quiet one: a picker offering a kind the
mapping table cannot resolve, which halts at ADR-0021 rule 3 on a kind that IS
registered. So the table is the authority and these files are its projection,
with the drift pinned by ``tests/test_kind_registry.py``.

WHERE THE DOMAIN WENT. ``ContentKindRegistration`` is ``extra="forbid"`` with
exactly ``kind``/``passes``/``outputs`` and no domain field — deliberately: the
SDK "does not ship any rows" and takes no position on domain, "the same reason
``iagent_mesh.task_kinds`` ships no domain species of its own." A ``domain:``
key in one of these YAML files would therefore RAISE, because the loader builds
each row via ``ContentKindRegistration(**raw)``. The declared domain is
published beside the rows in ``content_kind_domains.json`` instead, generated
in the same pass so it cannot drift from them, with ``null`` meaning the
ruling's "none (origin resolved by evidence, not kind)".

Usage::

    python scripts/generate_kind_registrations.py            # write
    python scripts/generate_kind_registrations.py --check    # exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from doc_tools.utils.content_kind import KIND_MAPPING  # noqa: E402

ROWS_DIR = REPO_ROOT / "registry" / "content_kinds"
DOMAINS_FILE = REPO_ROOT / "registry" / "content_kind_domains.json"

_HEADER = (
    "# GENERATED by scripts/generate_kind_registrations.py from\n"
    "# doc_tools/utils/content_kind.py's KIND_MAPPING. Do not edit by hand:\n"
    "# the mapping table is the authority and tests/test_kind_registry.py\n"
    "# fails on drift. A `domain:` key here would be refused by\n"
    "# ContentKindRegistration (extra=\"forbid\") — see content_kind_domains.json.\n"
)


def _yaml_list(values: tuple[str, ...]) -> str:
    return "".join(f"  - {v}\n" for v in values)


def render_row(entry) -> str:
    """One registration as YAML. Hand-rendered, not ``yaml.dump``: the files
    are read by humans deciding what a kind runs, and the generated header
    plus field order carry more than a dict dump would."""
    return (
        f"{_HEADER}"
        f"kind: {entry.kind}\n"
        f"passes:\n{_yaml_list(entry.passes)}"
        f"outputs:\n{_yaml_list(entry.outputs)}"
    )


def render_domains() -> str:
    """kind → declared domain, ``null`` for a format-level kind."""
    payload = {
        "_comment": (
            "GENERATED by scripts/generate_kind_registrations.py. The declared "
            "domain for each registered content kind. null means the kind "
            "declares NO domain (architect ruling 2026-10-02: origin resolved "
            "by evidence, not kind) -- such a drop lands in no domain graph and "
            "its stage is 'origin unresolved'. Lowercase here is the pipeline "
            "domain_type; the Neo4j label and the "
            "<http://internal/{DOMAIN}_INSTANCES> graph name are its uppercase."
        ),
        "domains": {
            entry.kind: entry.domain_type
            for entry in sorted(KIND_MAPPING.values(), key=lambda e: e.kind)
        },
    }
    return json.dumps(payload, indent=2) + "\n"


def expected_files() -> dict[Path, str]:
    files = {ROWS_DIR / f"{e.kind}.yaml": render_row(e) for e in KIND_MAPPING.values()}
    files[DOMAINS_FILE] = render_domains()
    return files


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk files match the table; write nothing")
    args = ap.parse_args()

    expected = expected_files()
    if args.check:
        drift = []
        for path, body in expected.items():
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != body:
                drift.append(f"{'MISSING' if actual is None else 'STALE'}: "
                             f"{path.relative_to(REPO_ROOT).as_posix()}")
        stray = [
            p for p in sorted(ROWS_DIR.glob("*.yaml")) if p not in expected
        ] if ROWS_DIR.exists() else []
        drift += [f"STRAY: {p.relative_to(REPO_ROOT).as_posix()}" for p in stray]
        if drift:
            print("\n".join(drift))
            print("Run: python scripts/generate_kind_registrations.py")
            return 1
        print(f"registry in sync with KIND_MAPPING ({len(KIND_MAPPING)} rows)")
        return 0

    ROWS_DIR.mkdir(parents=True, exist_ok=True)
    for path, body in expected.items():
        # newline="" so the LF the renderers emit is written verbatim. Without
        # it a Windows run translates every "\n" to "\r\n" and leaves all nine
        # files dirty with churn git then normalizes away -- which reads, in
        # `git status`, exactly like a generator that rewrote rows nobody
        # touched. Measured on 2026-10-07 while adding the `xml` row.
        path.write_text(body, encoding="utf-8", newline="")
    for p in sorted(ROWS_DIR.glob("*.yaml")):
        if p not in expected:
            p.unlink()
            print(f"removed stray {p.name}")
    print(f"wrote {len(expected)} files from {len(KIND_MAPPING)} KIND_MAPPING rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
