# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class Concept(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    related_terms: typing.List[str]
    salience: typing.Optional[float] = None

class LearningObjective(BaseModel):
    description: typing.Optional[str] = None

class ManufacturingStep(BaseModel):
    action: typing.Optional[str] = Field(default=None, description='The concrete action to take, e.g. \'Tighten bolt\'')
    tooling: typing.List[str] = Field(description='List of tools required, e.g. [\'Wrench\', \'Torque\'] If missing, empty list.')
    standard_ref: typing.Optional[str] = Field(default=None, description='e.g. \'ISO-9001\'. If none, leave null.')

class MatAugmentation(BaseModel):
    steps: typing.List["ManufacturingStep"]
    assessment: typing.Optional["StrategicAssessment"] = None

class Outline(BaseModel):
    sections: typing.List["Section"]

class Section(BaseModel):
    title: typing.Optional[str] = None
    level: typing.Optional[int] = None
    start_page: typing.Optional[int] = Field(default=None, description='The page number where this section begins based on the Table of Contents or page markers')
    end_page: typing.Optional[int] = Field(default=None, description='The page number where this section ends')
    subsections: typing.List["Section"]

class SlideAugmentation(BaseModel):
    concepts: typing.List["Concept"]
    objectives: typing.List["LearningObjective"]
    summary: typing.Optional[str] = None

class StrategicAssessment(BaseModel):
    proprietary_score: typing.Optional[float] = Field(default=None, description='0.0 (Common) to 1.0 (Secret Sauce). Score based on how specific/complex the process is.')
    outsourceable: typing.Optional[bool] = Field(default=None, description='If it requires secret sauce or highly sensitive MAT, true. Default to false if unclear.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
